# Site settings
title: 壳
subtitle: ╰每个人都有自己的缺陷,你需要用空杯的心态去吸收/学习新的知识 so...︶
description: 专注于移动互联网开发信息分享
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.im4j.com" # 你的域名
page_no_title: "无标题" # 文章无标题时默认显示内容
beian: # "备案号"
email: alafighting@163.com

duoshuo: alafighting # 多说ID

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

# Pageinate settings
paginate: 10 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 关于
    directory: about/
    icon: icon-about
  - page: 历史
    directory: history/
    icon: icon-history
  - page: 订阅
    directory: feed.xml
    icon: icon-rss

# Link settings
links: # 友情链接
  - title: Android_CJJ
    url: https://github.com/android-cjj
  - title: 代码家
    url: http://daimajia.com/
  - title: JieChic
    url: http://www.jiechic.com/
